version: "3.9"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "./running:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  wait_for_zookeeper:
    image: docker.io/briceburg/docker-compose-wait
    command:
      "wait"
    environment:
      - WAIT_HOSTS=zookeeper:8080
      - WAIT_TIMEOUT=120

  kafka:
    image: docker.io/bitnami/kafka:3.2.3
    ports:
      - "9092:9092"
    volumes:
      - "./running:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      wait_for_zookeeper:
        condition: service_completed_successfully

  wait_for_kafka:
    image: docker.io/briceburg/docker-compose-wait
    command:
      "wait"
    environment:
      - WAIT_HOSTS=kafka:9092
      - WAIT_TIMEOUT=120

  efak:
    image: docker.io/trivadis/efak
    ports:
      - "8048:8048"
    environment:
      - ZKSERVER=zookeeper:2181
    depends_on:
      - wait_for_zookeeper
      - wait_for_kafka

  etcd:
    image: docker.io/bitnami/etcd
    ports:
      - "2379:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes

  redis:
    image: docker.io/redis:6.2.7
    ports:
      - "6379:6379"

  mysql:
    image: docker.io/mysql:5.7.40
    ports:
      - "3306:3306"
    volumes:
      - "./running/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=default_database
      - MYSQL_USER=not_a_user
      - MYSQL_PASSWORD=password

  mongo:
    image: docker.io/mongo:6.0.2
    ports:
      - "27017:27017"
    volumes:
      - "./running/mongodb:/data/db"

  wait_for_all_remained:
    image: docker.io/briceburg/docker-compose-wait
    command:
      "wait"
    environment:
      - WAIT_HOSTS=etcd:2379, redis:6379, mysql:3306, mongo:27017
      - WAIT_TIMEOUT=120

  livechat:
    image: docker.io/a47451516/livechat:latest
    ports:
      - "1234:1235"
      - "1345:1345"
      - "5678:5678"
    volumes:
      - "./default_config_files:/appdata/config"
    environment:
      - MONGO_ADDRESS=mongodb://mongo:27017/default_database
      - MYSQL_ADDRESS=root:password@tcp(mysql:3306)/default_database?parseTime=true
      - REDIS_ADDRESS=redis://redis:6379/0
      - NOTIFICATION_QUEUE_URL=kafka:9092
      - MESSAGE_QUEUE_URL=kafka:9092
      - ETCD_ADDRESS=etcd:2379
    depends_on:
      wait_for_kafka:
        condition: service_completed_successfully
      wait_for_all_remained:
        condition: service_completed_successfully

