// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.8.0
// source: cs_message.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageContentType int32

const (
	Message_Text  MessageContentType = 0
	Message_Image MessageContentType = 1
	Message_Emoji MessageContentType = 2
)

// Enum value maps for MessageContentType.
var (
	MessageContentType_name = map[int32]string{
		0: "Text",
		1: "Image",
		2: "Emoji",
	}
	MessageContentType_value = map[string]int32{
		"Text":  0,
		"Image": 1,
		"Emoji": 2,
	}
)

func (x MessageContentType) Enum() *MessageContentType {
	p := new(MessageContentType)
	*p = x
	return p
}

func (x MessageContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_cs_message_proto_enumTypes[0].Descriptor()
}

func (MessageContentType) Type() protoreflect.EnumType {
	return &file_cs_message_proto_enumTypes[0]
}

func (x MessageContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageContentType.Descriptor instead.
func (MessageContentType) EnumDescriptor() ([]byte, []int) {
	return file_cs_message_proto_rawDescGZIP(), []int{1, 0}
}

type RequestEstablishConnectionPlatformType int32

const (
	RequestEstablishConnection_Web     RequestEstablishConnectionPlatformType = 0
	RequestEstablishConnection_Android RequestEstablishConnectionPlatformType = 1
)

// Enum value maps for RequestEstablishConnectionPlatformType.
var (
	RequestEstablishConnectionPlatformType_name = map[int32]string{
		0: "Web",
		1: "Android",
	}
	RequestEstablishConnectionPlatformType_value = map[string]int32{
		"Web":     0,
		"Android": 1,
	}
)

func (x RequestEstablishConnectionPlatformType) Enum() *RequestEstablishConnectionPlatformType {
	p := new(RequestEstablishConnectionPlatformType)
	*p = x
	return p
}

func (x RequestEstablishConnectionPlatformType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestEstablishConnectionPlatformType) Descriptor() protoreflect.EnumDescriptor {
	return file_cs_message_proto_enumTypes[1].Descriptor()
}

func (RequestEstablishConnectionPlatformType) Type() protoreflect.EnumType {
	return &file_cs_message_proto_enumTypes[1]
}

func (x RequestEstablishConnectionPlatformType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestEstablishConnectionPlatformType.Descriptor instead.
func (RequestEstablishConnectionPlatformType) EnumDescriptor() ([]byte, []int) {
	return file_cs_message_proto_rawDescGZIP(), []int{5, 0}
}

type ErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cs_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_cs_message_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64             `protobuf:"fixed64,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender    int64              `protobuf:"fixed64,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver  int64              `protobuf:"fixed64,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Timestamp uint64             `protobuf:"fixed64,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type      MessageContentType `protobuf:"varint,5,opt,name=type,proto3,enum=MessageContentType" json:"type,omitempty"`
	Contents  []string           `protobuf:"bytes,6,rep,name=contents,proto3" json:"contents,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_cs_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_cs_message_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetSender() int64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *Message) GetReceiver() int64 {
	if x != nil {
		return x.Receiver
	}
	return 0
}

func (x *Message) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message) GetType() MessageContentType {
	if x != nil {
		return x.Type
	}
	return Message_Text
}

func (x *Message) GetContents() []string {
	if x != nil {
		return x.Contents
	}
	return nil
}

type RequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64 `protobuf:"fixed64,1,opt,name=id,proto3" json:"id,omitempty"`
	Receiver int64  `protobuf:"fixed64,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
}

func (x *RequestMessage) Reset() {
	*x = RequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMessage) ProtoMessage() {}

func (x *RequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cs_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMessage.ProtoReflect.Descriptor instead.
func (*RequestMessage) Descriptor() ([]byte, []int) {
	return file_cs_message_proto_rawDescGZIP(), []int{2}
}

func (x *RequestMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RequestMessage) GetReceiver() int64 {
	if x != nil {
		return x.Receiver
	}
	return 0
}

type MultiMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *MultiMessage) Reset() {
	*x = MultiMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiMessage) ProtoMessage() {}

func (x *MultiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cs_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiMessage.ProtoReflect.Descriptor instead.
func (*MultiMessage) Descriptor() ([]byte, []int) {
	return file_cs_message_proto_rawDescGZIP(), []int{3}
}

func (x *MultiMessage) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type RequestMultiMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BottomId uint64 `protobuf:"fixed64,1,opt,name=bottomId,proto3" json:"bottomId,omitempty"`
	TopId    uint64 `protobuf:"fixed64,2,opt,name=topId,proto3" json:"topId,omitempty"`
	Receiver int64  `protobuf:"fixed64,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
}

func (x *RequestMultiMessage) Reset() {
	*x = RequestMultiMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestMultiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMultiMessage) ProtoMessage() {}

func (x *RequestMultiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cs_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMultiMessage.ProtoReflect.Descriptor instead.
func (*RequestMultiMessage) Descriptor() ([]byte, []int) {
	return file_cs_message_proto_rawDescGZIP(), []int{4}
}

func (x *RequestMultiMessage) GetBottomId() uint64 {
	if x != nil {
		return x.BottomId
	}
	return 0
}

func (x *RequestMultiMessage) GetTopId() uint64 {
	if x != nil {
		return x.TopId
	}
	return 0
}

func (x *RequestMultiMessage) GetReceiver() int64 {
	if x != nil {
		return x.Receiver
	}
	return 0
}

type RequestEstablishConnection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token    string                                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Platform RequestEstablishConnectionPlatformType `protobuf:"varint,2,opt,name=platform,proto3,enum=RequestEstablishConnectionPlatformType" json:"platform,omitempty"`
}

func (x *RequestEstablishConnection) Reset() {
	*x = RequestEstablishConnection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestEstablishConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEstablishConnection) ProtoMessage() {}

func (x *RequestEstablishConnection) ProtoReflect() protoreflect.Message {
	mi := &file_cs_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEstablishConnection.ProtoReflect.Descriptor instead.
func (*RequestEstablishConnection) Descriptor() ([]byte, []int) {
	return file_cs_message_proto_rawDescGZIP(), []int{5}
}

func (x *RequestEstablishConnection) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RequestEstablishConnection) GetPlatform() RequestEstablishConnectionPlatformType {
	if x != nil {
		return x.Platform
	}
	return RequestEstablishConnection_Web
}

type ResponseEstablishConnection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateChat []int64 `protobuf:"fixed64,1,rep,packed,name=privateChat,proto3" json:"privateChat,omitempty"`
	GroupChat   []int64 `protobuf:"fixed64,2,rep,packed,name=groupChat,proto3" json:"groupChat,omitempty"`
}

func (x *ResponseEstablishConnection) Reset() {
	*x = ResponseEstablishConnection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseEstablishConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseEstablishConnection) ProtoMessage() {}

func (x *ResponseEstablishConnection) ProtoReflect() protoreflect.Message {
	mi := &file_cs_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseEstablishConnection.ProtoReflect.Descriptor instead.
func (*ResponseEstablishConnection) Descriptor() ([]byte, []int) {
	return file_cs_message_proto_rawDescGZIP(), []int{6}
}

func (x *ResponseEstablishConnection) GetPrivateChat() []int64 {
	if x != nil {
		return x.PrivateChat
	}
	return nil
}

func (x *ResponseEstablishConnection) GetGroupChat() []int64 {
	if x != nil {
		return x.GroupChat
	}
	return nil
}

var File_cs_message_proto protoreflect.FileDescriptor

var file_cs_message_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x73, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x27, 0x0a, 0x0d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0xe0, 0x01, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x06, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x10, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x10, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x06, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x22,
	0x2d, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08,
	0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x6d, 0x6f, 0x6a, 0x69, 0x10, 0x02, 0x22, 0x3c,
	0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x10, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x22, 0x34, 0x0a, 0x0c,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x24, 0x0a, 0x08,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x22, 0x63, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x6f, 0x74,
	0x74, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x08, 0x62, 0x6f, 0x74,
	0x74, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x06, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x10, 0x52, 0x08, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x22, 0x9e, 0x01, 0x0a, 0x1a, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x45, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x44, 0x0a, 0x08,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x22, 0x24, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x57, 0x65, 0x62, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41,
	0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x10, 0x01, 0x22, 0x5d, 0x0a, 0x1b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x45, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x10, 0x52, 0x0b, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x43, 0x68, 0x61, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x10, 0x52, 0x09, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x43, 0x68, 0x61, 0x74, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cs_message_proto_rawDescOnce sync.Once
	file_cs_message_proto_rawDescData = file_cs_message_proto_rawDesc
)

func file_cs_message_proto_rawDescGZIP() []byte {
	file_cs_message_proto_rawDescOnce.Do(func() {
		file_cs_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_cs_message_proto_rawDescData)
	})
	return file_cs_message_proto_rawDescData
}

var file_cs_message_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cs_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cs_message_proto_goTypes = []interface{}{
	(MessageContentType)(0),                     // 0: Message.contentType
	(RequestEstablishConnectionPlatformType)(0), // 1: RequestEstablishConnection.platformType
	(*ErrorResponse)(nil),                       // 2: ErrorResponse
	(*Message)(nil),                             // 3: Message
	(*RequestMessage)(nil),                      // 4: RequestMessage
	(*MultiMessage)(nil),                        // 5: MultiMessage
	(*RequestMultiMessage)(nil),                 // 6: RequestMultiMessage
	(*RequestEstablishConnection)(nil),          // 7: RequestEstablishConnection
	(*ResponseEstablishConnection)(nil),         // 8: ResponseEstablishConnection
}
var file_cs_message_proto_depIdxs = []int32{
	0, // 0: Message.type:type_name -> Message.contentType
	3, // 1: MultiMessage.messages:type_name -> Message
	1, // 2: RequestEstablishConnection.platform:type_name -> RequestEstablishConnection.platformType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cs_message_proto_init() }
func file_cs_message_proto_init() {
	if File_cs_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cs_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestMultiMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestEstablishConnection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseEstablishConnection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cs_message_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cs_message_proto_goTypes,
		DependencyIndexes: file_cs_message_proto_depIdxs,
		EnumInfos:         file_cs_message_proto_enumTypes,
		MessageInfos:      file_cs_message_proto_msgTypes,
	}.Build()
	File_cs_message_proto = out.File
	file_cs_message_proto_rawDesc = nil
	file_cs_message_proto_goTypes = nil
	file_cs_message_proto_depIdxs = nil
}
