// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.8.0
// source: micro_call.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KickOffRequest_PlatformType int32

const (
	KickOffRequest_Web     KickOffRequest_PlatformType = 0
	KickOffRequest_Android KickOffRequest_PlatformType = 1
)

// Enum value maps for KickOffRequest_PlatformType.
var (
	KickOffRequest_PlatformType_name = map[int32]string{
		0: "Web",
		1: "Android",
	}
	KickOffRequest_PlatformType_value = map[string]int32{
		"Web":     0,
		"Android": 1,
	}
)

func (x KickOffRequest_PlatformType) Enum() *KickOffRequest_PlatformType {
	p := new(KickOffRequest_PlatformType)
	*p = x
	return p
}

func (x KickOffRequest_PlatformType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KickOffRequest_PlatformType) Descriptor() protoreflect.EnumDescriptor {
	return file_micro_call_proto_enumTypes[0].Descriptor()
}

func (KickOffRequest_PlatformType) Type() protoreflect.EnumType {
	return &file_micro_call_proto_enumTypes[0]
}

func (x KickOffRequest_PlatformType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KickOffRequest_PlatformType.Descriptor instead.
func (KickOffRequest_PlatformType) EnumDescriptor() ([]byte, []int) {
	return file_micro_call_proto_rawDescGZIP(), []int{1, 0}
}

type NotificationRequest_OpType int32

const (
	NotificationRequest_Add     NotificationRequest_OpType = 0
	NotificationRequest_Delete  NotificationRequest_OpType = 1
	NotificationRequest_Approve NotificationRequest_OpType = 2
	NotificationRequest_Refuse  NotificationRequest_OpType = 3
)

// Enum value maps for NotificationRequest_OpType.
var (
	NotificationRequest_OpType_name = map[int32]string{
		0: "Add",
		1: "Delete",
		2: "Approve",
		3: "Refuse",
	}
	NotificationRequest_OpType_value = map[string]int32{
		"Add":     0,
		"Delete":  1,
		"Approve": 2,
		"Refuse":  3,
	}
)

func (x NotificationRequest_OpType) Enum() *NotificationRequest_OpType {
	p := new(NotificationRequest_OpType)
	*p = x
	return p
}

func (x NotificationRequest_OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationRequest_OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_micro_call_proto_enumTypes[1].Descriptor()
}

func (NotificationRequest_OpType) Type() protoreflect.EnumType {
	return &file_micro_call_proto_enumTypes[1]
}

func (x NotificationRequest_OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationRequest_OpType.Descriptor instead.
func (NotificationRequest_OpType) EnumDescriptor() ([]byte, []int) {
	return file_micro_call_proto_rawDescGZIP(), []int{2, 0}
}

type NotificationRequest_ReceiveType int32

const (
	NotificationRequest_User          NotificationRequest_ReceiveType = 0
	NotificationRequest_Group         NotificationRequest_ReceiveType = 1
	NotificationRequest_Administrator NotificationRequest_ReceiveType = 2
)

// Enum value maps for NotificationRequest_ReceiveType.
var (
	NotificationRequest_ReceiveType_name = map[int32]string{
		0: "User",
		1: "Group",
		2: "Administrator",
	}
	NotificationRequest_ReceiveType_value = map[string]int32{
		"User":          0,
		"Group":         1,
		"Administrator": 2,
	}
)

func (x NotificationRequest_ReceiveType) Enum() *NotificationRequest_ReceiveType {
	p := new(NotificationRequest_ReceiveType)
	*p = x
	return p
}

func (x NotificationRequest_ReceiveType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationRequest_ReceiveType) Descriptor() protoreflect.EnumDescriptor {
	return file_micro_call_proto_enumTypes[2].Descriptor()
}

func (NotificationRequest_ReceiveType) Type() protoreflect.EnumType {
	return &file_micro_call_proto_enumTypes[2]
}

func (x NotificationRequest_ReceiveType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationRequest_ReceiveType.Descriptor instead.
func (NotificationRequest_ReceiveType) EnumDescriptor() ([]byte, []int) {
	return file_micro_call_proto_rawDescGZIP(), []int{2, 1}
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId            uint64 `protobuf:"fixed64,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	IsProcessedByOneSelf bool   `protobuf:"varint,2,opt,name=isProcessedByOneSelf,proto3" json:"isProcessedByOneSelf,omitempty"`
	IsSucceeded          bool   `protobuf:"varint,3,opt,name=isSucceeded,proto3" json:"isSucceeded,omitempty"`
	FailureReason        string `protobuf:"bytes,4,opt,name=failureReason,proto3" json:"failureReason,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_micro_call_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_micro_call_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_micro_call_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Response) GetIsProcessedByOneSelf() bool {
	if x != nil {
		return x.IsProcessedByOneSelf
	}
	return false
}

func (x *Response) GetIsSucceeded() bool {
	if x != nil {
		return x.IsSucceeded
	}
	return false
}

func (x *Response) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

type KickOffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId uint64                      `protobuf:"fixed64,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	UserId    int64                       `protobuf:"fixed64,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Platform  KickOffRequest_PlatformType `protobuf:"varint,3,opt,name=platform,proto3,enum=KickOffRequest_PlatformType" json:"platform,omitempty"`
}

func (x *KickOffRequest) Reset() {
	*x = KickOffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_micro_call_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KickOffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickOffRequest) ProtoMessage() {}

func (x *KickOffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_micro_call_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickOffRequest.ProtoReflect.Descriptor instead.
func (*KickOffRequest) Descriptor() ([]byte, []int) {
	return file_micro_call_proto_rawDescGZIP(), []int{1}
}

func (x *KickOffRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *KickOffRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *KickOffRequest) GetPlatform() KickOffRequest_PlatformType {
	if x != nil {
		return x.Platform
	}
	return KickOffRequest_Web
}

type NotificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId       uint64                          `protobuf:"fixed64,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Id              uint64                          `protobuf:"fixed64,2,opt,name=id,proto3" json:"id,omitempty"`
	Sender          int64                           `protobuf:"fixed64,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver        int64                           `protobuf:"fixed64,4,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Timestamp       uint64                          `protobuf:"fixed64,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Op              NotificationRequest_OpType      `protobuf:"varint,6,opt,name=op,proto3,enum=NotificationRequest_OpType" json:"op,omitempty"`
	ReceiveType     NotificationRequest_ReceiveType `protobuf:"varint,7,opt,name=receiveType,proto3,enum=NotificationRequest_ReceiveType" json:"receiveType,omitempty"`
	IsHandledByAuth bool                            `protobuf:"varint,8,opt,name=isHandledByAuth,proto3" json:"isHandledByAuth,omitempty"`
	IsAgree         bool                            `protobuf:"varint,9,opt,name=isAgree,proto3" json:"isAgree,omitempty"`
}

func (x *NotificationRequest) Reset() {
	*x = NotificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_micro_call_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationRequest) ProtoMessage() {}

func (x *NotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_micro_call_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationRequest.ProtoReflect.Descriptor instead.
func (*NotificationRequest) Descriptor() ([]byte, []int) {
	return file_micro_call_proto_rawDescGZIP(), []int{2}
}

func (x *NotificationRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *NotificationRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NotificationRequest) GetSender() int64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *NotificationRequest) GetReceiver() int64 {
	if x != nil {
		return x.Receiver
	}
	return 0
}

func (x *NotificationRequest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *NotificationRequest) GetOp() NotificationRequest_OpType {
	if x != nil {
		return x.Op
	}
	return NotificationRequest_Add
}

func (x *NotificationRequest) GetReceiveType() NotificationRequest_ReceiveType {
	if x != nil {
		return x.ReceiveType
	}
	return NotificationRequest_User
}

func (x *NotificationRequest) GetIsHandledByAuth() bool {
	if x != nil {
		return x.IsHandledByAuth
	}
	return false
}

func (x *NotificationRequest) GetIsAgree() bool {
	if x != nil {
		return x.IsAgree
	}
	return false
}

type MessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId uint64   `protobuf:"fixed64,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Message   *Message `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MessageRequest) Reset() {
	*x = MessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_micro_call_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequest) ProtoMessage() {}

func (x *MessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_micro_call_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequest.ProtoReflect.Descriptor instead.
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return file_micro_call_proto_rawDescGZIP(), []int{3}
}

func (x *MessageRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *MessageRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_micro_call_proto protoreflect.FileDescriptor

var file_micro_call_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x10, 0x63, 0x73, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa4, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x06, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12,
	0x32, 0x0a, 0x14, 0x69, 0x73, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x42, 0x79,
	0x4f, 0x6e, 0x65, 0x53, 0x65, 0x6c, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x14, 0x69,
	0x73, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x42, 0x79, 0x4f, 0x6e, 0x65, 0x53,
	0x65, 0x6c, 0x66, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x65, 0x64, 0x65, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65,
	0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x61,
	0x69, 0x6c, 0x75, 0x72, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0xa6, 0x01, 0x0a, 0x0e,
	0x4b, 0x69, 0x63, 0x6b, 0x4f, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x06, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x10, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x4b, 0x69, 0x63, 0x6b, 0x4f, 0x66, 0x66,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0x24,
	0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07,
	0x0a, 0x03, 0x57, 0x65, 0x62, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x6e, 0x64, 0x72, 0x6f,
	0x69, 0x64, 0x10, 0x01, 0x22, 0xb9, 0x03, 0x0a, 0x13, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52,
	0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x10, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x10, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x06, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2b, 0x0a, 0x02,
	0x6f, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f,
	0x70, 0x54, 0x79, 0x70, 0x65, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x42, 0x0a, 0x0b, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20,
	0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a,
	0x0f, 0x69, 0x73, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x64, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x69, 0x73, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x64, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x41, 0x67, 0x72,
	0x65, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x41, 0x67, 0x72, 0x65,
	0x65, 0x22, 0x36, 0x0a, 0x06, 0x4f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x41,
	0x64, 0x64, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x10, 0x01,
	0x12, 0x0b, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x10, 0x02, 0x12, 0x0a, 0x0a,
	0x06, 0x52, 0x65, 0x66, 0x75, 0x73, 0x65, 0x10, 0x03, 0x22, 0x35, 0x0a, 0x0b, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x10, 0x01, 0x12, 0x11, 0x0a,
	0x0d, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x10, 0x02,
	0x22, 0x52, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64,
	0x12, 0x22, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x32, 0xb9, 0x01, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e,
	0x6f, 0x64, 0x65, 0x12, 0x3d, 0x0a, 0x1d, 0x4b, 0x69, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x4f,
	0x66, 0x66, 0x4f, 0x6e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x50, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x12, 0x0f, 0x2e, 0x4b, 0x69, 0x63, 0x6b, 0x4f, 0x66, 0x66, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x3a, 0x0a, 0x15, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x2e, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x30,
	0x0a, 0x10, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x0f, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_micro_call_proto_rawDescOnce sync.Once
	file_micro_call_proto_rawDescData = file_micro_call_proto_rawDesc
)

func file_micro_call_proto_rawDescGZIP() []byte {
	file_micro_call_proto_rawDescOnce.Do(func() {
		file_micro_call_proto_rawDescData = protoimpl.X.CompressGZIP(file_micro_call_proto_rawDescData)
	})
	return file_micro_call_proto_rawDescData
}

var file_micro_call_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_micro_call_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_micro_call_proto_goTypes = []interface{}{
	(KickOffRequest_PlatformType)(0),     // 0: KickOffRequest.PlatformType
	(NotificationRequest_OpType)(0),      // 1: NotificationRequest.OpType
	(NotificationRequest_ReceiveType)(0), // 2: NotificationRequest.ReceiveType
	(*Response)(nil),                     // 3: Response
	(*KickOffRequest)(nil),               // 4: KickOffRequest
	(*NotificationRequest)(nil),          // 5: NotificationRequest
	(*MessageRequest)(nil),               // 6: MessageRequest
	(*Message)(nil),                      // 7: Message
}
var file_micro_call_proto_depIdxs = []int32{
	0, // 0: KickOffRequest.platform:type_name -> KickOffRequest.PlatformType
	1, // 1: NotificationRequest.op:type_name -> NotificationRequest.OpType
	2, // 2: NotificationRequest.receiveType:type_name -> NotificationRequest.ReceiveType
	7, // 3: MessageRequest.message:type_name -> Message
	4, // 4: ServerNode.KickUserOffOnSpecificPlatform:input_type -> KickOffRequest
	5, // 5: ServerNode.BroadcastNotification:input_type -> NotificationRequest
	6, // 6: ServerNode.BroadcastMessage:input_type -> MessageRequest
	3, // 7: ServerNode.KickUserOffOnSpecificPlatform:output_type -> Response
	3, // 8: ServerNode.BroadcastNotification:output_type -> Response
	3, // 9: ServerNode.BroadcastMessage:output_type -> Response
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_micro_call_proto_init() }
func file_micro_call_proto_init() {
	if File_micro_call_proto != nil {
		return
	}
	file_cs_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_micro_call_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_micro_call_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KickOffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_micro_call_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_micro_call_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_micro_call_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_micro_call_proto_goTypes,
		DependencyIndexes: file_micro_call_proto_depIdxs,
		EnumInfos:         file_micro_call_proto_enumTypes,
		MessageInfos:      file_micro_call_proto_msgTypes,
	}.Build()
	File_micro_call_proto = out.File
	file_micro_call_proto_rawDesc = nil
	file_micro_call_proto_goTypes = nil
	file_micro_call_proto_depIdxs = nil
}
